version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/prosit2
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
